# Generated by Django 5.2 on 2025-05-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название курса')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('notebook', models.FileField(blank=True, null=True, upload_to='course_files', verbose_name='Блокнот')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название задания')),
                ('up_code', models.TextField(blank=True, null=True, verbose_name='Код, выше кода пользователя')),
                ('down_code', models.TextField(blank=True, null=True, verbose_name='Код, ниже кода пользователя')),
                ('open_assert', models.TextField(blank=True, null=True, verbose_name='Открытые тесты')),
                ('close_assert', models.TextField(blank=True, null=True, verbose_name='Закрытые тесты')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('time', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Время')),
                ('memory', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Память')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courses')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'task',
            },
        ),
    ]
